services:
  scrapper:
    build:
      context: ../../source
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    environment:
      - DJANGO_SETTINGS_MODULE=vpscrapproject.settings
      - ALLOWED_HOSTS=${APP_ALLOWED_HOSTS}
      - APP_HOST_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - DB_ENGINE=${APP_DB_ENGINE}
      - DB_HOST=${APP_DB_NAME}
      - DB_DB=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - CELERY_BACKEND=redis://scrapper-redis:6379/0
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq//
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - ../../source/vpscrapproject/:/app/
    healthcheck:
      test: curl --fail http://0.0.0.0:${APP_PORT}/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    depends_on:
      scrapper-db:
        condition: service_healthy
      celery_worker:
        condition: service_started
    ports:
      - "8002:${APP_PORT}"
    networks:
      - network_back
      - network_front

  scrapper-db:
    image: postgres:13
    container_name: ${APP_DB_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./scrapper-db/:/var/lib/postgresql/data/
    networks:
      - network_back

  selenium:
    image: selenium/standalone-chrome:4.8.3-20230328
    container_name: ${SELENIUM_NAME}
    ports:
    - "4444:${SELENIUM_PORT}"
    networks:
      - network_back
      - network_front

  celery_worker:
    build:
      context: ../../source
      dockerfile: Dockerfile
    networks:
      - network_back
    container_name: celery_worker
    hostname: celery_worker
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      selenium:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=vpscrapproject.settings
      - TZ=${TZ}
      - CELERY_BACKEND=redis://scrapper-redis:6379/0
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq//
      - SELENIUM_HOST=${SELENIUM_NAME}
      - SELENIUM_PORT=${SELENIUM_PORT}
    command: ['celery', '-A', 'vpscrapproject.celery', 'worker', '-l', 'info']


  celery_beat:
    build:
      context: ../../source
      dockerfile: Dockerfile
    networks:
      - network_back
    container_name: celery_beat
    hostname: celery_beat
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - TZ=${TZ}
    command: [ 'celery', '-A', 'vpscrapproject.celery', 'beat', '-l', 'info']

  redis:
    image: redis:7.0.9-alpine
    container_name: scrapper-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network_back
    volumes:
      - ./redis/:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    user: "1000:1000"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network_back
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
      - ./rabbitmq/etc/:/etc/rabbitmq/

    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      - TZ=${TZ}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

networks:
  network_front:
    driver: bridge
    name: scrapper_network_front
  network_back:
    driver: bridge
    name: scrapper_network_back
    internal: true
